### ISSUE TITLE
Configurable token.dat path

### ISSUE THREAD

**Issue by prestonvanloon** [Alethio/eth2stats-client#1]
Would it be possible to provide a path via flag for the token.dat? 
This would help us add eth2stats client in our deployments.

**Comment by tzapu** [comment]
sure, will prioritize it
seeing how docker creates folders when given a volume that does not exist on the host, would it be ok to have a customizable config so you can specify `-v /local/config/folder:/config` ?
would you then also need to change the `/config` part?

p.s. excuse the current poor documentation, super WIP

**Comment by tzapu** [comment]
btw @prestonvanloon , for now you can also just not mount it, if the key is lost on pod/container recreation, a new entry with the same name will appear on the portal, the old one will appear offline and will be cleaned up after a few hours

**Comment by prestonvanloon** [comment]
I don't mind mounting a config volume, but the token path is not in the config path.

https://github.com/Alethio/eth2stats-client/blob/ee16e1e4dca4c4275e47a2905c8ca11e40763621/core/token.go#L11

**Comment by tzapu** [comment]
oh yeah, made the change here https://github.com/Alethio/eth2stats-client/pull/3/files#diff-2c824df4dc0776b6848cf5e02e9d5f07R13
as soon as it's reviewed i ll ping you

**Comment by tzapu** [comment]
hey @prestonvanloon this was merged.
can you try with
```
docker run -d --name eth2stats --restart always --network="host" \
    alethio/eth2stats-client:latest \
    run --v \
    -v /path/to/your/persistant/data/folder:/data \
    --eth2stats.node-name="YourNode" \ 
    --data-folder="/data" \
    --eth2stats.addr="grpc.sapphire.eth2stats.net:443" --eth2stats.tls=true \
    --beacon.type="prysm" --beacon.addr="localhost:4000"
```

**Comment by kwix** [comment]
Will close this since the feature has been implemented.
