### ISSUE TITLE
Timestamp in log

### ISSUE THREAD

**Issue by handelaar2** [Alethio/eth2stats-client#11]
Currently the log entries do not show a timestamp. It would be nice to see when a log-entry is actually printed. This way we have a "time reference".

WARN[2639] [core] ChainHead request was skipped due to rate limiting 
INFO[2641] [prysm] got chain head                        headSlot=67504
INFO[2643] [prysm] got chain head                        headSlot=67505
INFO[2644] [prysm] got chain head                        headSlot=67506
INFO[2646] [prysm] got chain head                        headSlot=67507
INFO[2648] [prysm] got chain head                        headSlot=67508
INFO[2650] [prysm] got chain head                        headSlot=67509
INFO[2652] [prysm] got chain head                        headSlot=67510
INFO[2653] [prysm] got chain head                        headSlot=67511
INFO[2655] [prysm] got chain head                        headSlot=67512
INFO[2657] [prysm] got chain head                        headSlot=67513
INFO[2659] [prysm] got chain head                        headSlot=67514
INFO[2659] [prysm] got chain head                        headSlot=67515
WARN[2659] [core] ChainHead request was skipped due to rate limiting 
INFO[2661] [prysm] got chain head                        headSlot=67516
INFO[2662] [prysm] got chain head                        headSlot=67517
WARN[2662] [core] ChainHead request was skipped due to rate limiting 
INFO[2664] [prysm] got chain head                        headSlot=67518

**Comment by tzapu** [comment]
hi, i think that s just the log formatted for an interarctive console. the plain text logs contain timestamps (so the ones you would collect in kubernetes or something). 

will see what we can do

**Comment by handelaar2** [comment]
Yes, this in the interactive console output. Im not using kubernetes but portainer to manage my docker container (and eth2stats is one of those). This is how it looks in portainer.
<img width="852" alt="Screenshot 2020-01-20 at 17 18 23" src="https://user-images.githubusercontent.com/28559038/72742087-4e74a300-3ba9-11ea-9587-b3053685be02.png">

**Comment by handelaar2** [comment]
One additional question: Does it mean (see screen print) that the headSlot is sent multiple times?
(needed?)

<img width="605" alt="Screenshot 2020-01-22 at 17 21 39" src="https://user-images.githubusercontent.com/28559038/72912883-9415a500-3d3c-11ea-8c55-588c70ca9823.png">

**Comment by tzapu** [comment]
that is coming straight from the grpc stream to prysm, so it looks like it was sent multiple times
https://github.com/Alethio/eth2stats-client/blob/a42bf4efc7afc2604f80aebb23c6676e337d6fdf/beacon/prysm/subscription.go#L38

those are most likely some reorg/forks but it's hard to tell just from the slot, without all the data in the head (some other root might have changed for instance)

**Comment by tzapu** [comment]
just added the timestamp option @handelaar2 , please pull the latest request and add arg
`--logging.full-timestamps=true`
let me know if it works ok for you

**Comment by handelaar2** [comment]
hi @tzapu looks great! Thanks!

<img width="1340" alt="Screenshot 2020-01-23 at 08 20 24" src="https://user-images.githubusercontent.com/28559038/72964268-b4d01000-3db9-11ea-951f-3c4eb8ea255d.png">
