### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by mangoleap** [Alethio/eth2stats-client#14]
Trying to build the repo on a NANOPC T4. This is the output:

> root@ethnode-9538ecf1:~/eth2stats-client# make build
go build -ldflags "-X main.buildVersion="v0.0.3-872141e""
main.go:7:2: cannot find package "github.com/alethio/eth2stats-client/commands" in any of:
	/usr/lib/go-1.10/src/github.com/alethio/eth2stats-client/commands (from $GOROOT)
	/root/eth2stats-client/src/github.com/alethio/eth2stats-client/commands (from $GOPATH)
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1

Not really familiar with go. Do you git any hints?

**Comment by tzapu** [comment]
hey, i m not familiar with the nanopc t4 nor have we tried to build it on arm so shooting in the dark here
what version of go have you got installed? `go version` in console

**Comment by eliaskg** [comment]
Just tried it under a regular Linux machine (Debian, X86), unfortunately with the same result.

go version go1.7.4 linux/amd64

**Comment by kwix** [comment]
Hey @eliaskg ! You need `go 1.11` minimum to be able to build it. Earlier versions, like you have there, lack go modules support.

**Comment by eliaskg** [comment]
Thanks @kwix! Now I'm one step further and it starts building. However it produced a checksum error for a certain package now. I already tried `go clean -modcache`.

> verifying github.com/ugorji/go/codec@v1.1.7: checksum mismatch
> 	downloaded: h1:2SvQaVZ1ouYrrKKwoSk2pzd4A9evlKJb9oTL+OaLUSs=
> 	go.sum:     h1:zVRFvIPbjpIMl2pf6vLXZTYXTo13zccQOe/LjQ3dqP8=
> 
> SECURITY ERROR
> This download does NOT match an earlier download recorded in go.sum.
> The bits may have been replaced on the origin server, or an attacker may
> have intercepted the download attempt.
> 
> For more information, see 'go help module-auth'.
> Makefile:4: recipe for target 'build' failed
> make: *** [build] Error 1

**Comment by tzapu** [comment]
maybe it's still something related to the go version, could you confirm what go version you are running now?

if it's 1.13 or higher you might want to try disabling the now by default enabled google proxy and checksum, just as a test
```
go env -w GOPROXY=direct
go env -w GOSUMDB=off
```

**Comment by tzapu** [comment]
in addition to the above, could you maybe also try branch https://github.com/Alethio/eth2stats-client/tree/replace-codec-version ? i tried to override that packages's version so it's fixed

**Comment by tzapu** [comment]
i have merged this, hopefully it will cause less issues. feel free to reopen if you still have issues
