### ISSUE TITLE
Fatal upstream request timeout

### ISSUE THREAD

**Issue by prestonvanloon** [Alethio/eth2stats-client#22]
time="2020-02-13T08:57:53Z" level=error msg="[prysm] rpc error: code = Unavailable desc = UNAVAILABLE:upstream request timeout"
time="2020-02-13T08:57:53Z" level=fatal msg="[telemetry] rpc error: code = Unavailable desc = UNAVAILABLE:upstream request timeout"

Docker image was `alethio/eth2stats-client@sha256:a0b388460afcaf3a336fb47ef188eede0a5b92760a72fd0b1ec3e77025055f31`

**Comment by tzapu** [comment]
hi @prestonvanloon is this persistent or just happened once? 
i can't tell 100% but it might be the connection between eth2stats cli and prysm. if possible could you also update to latest? added some more detailed error messages
cheers

**Comment by prestonvanloon** [comment]
Updated to latest image. I'll let you know if we see more issues. Thanks!
