### ISSUE TITLE
Cannot connect to beacon node

### ISSUE THREAD

**Issue by Youllneverknow0** [Alethio/eth2stats-client#24]
running eth2stats gives the following error:

FATA[0000] [core] invalid node URL: localhost:5052

I run eth2stats with the following parameter:

./eth2stats-client run \
        --eth2stats.node-name="ethnode-c65e37164" \
        --eth2stats.addr="grc.summer.eth2stats.io:443" \
        --eth2stats.tls=true \
        --beacon.type="lighthouse" \
        --beacon.addr="localhost:5052" \
        --beacon.metrics-addr="http://localhost:8080/metrics"

lighthouse is up and running fine.

A short glimpse to the used ports with sudo lsof -i -P -n | grep LISTEN
gives the following output

lighthous  3962          ubuntu   30u  IPv4  728231      0t0  TCP *:9000 (LISTEN)
lighthous  3962          ubuntu   35u  IPv4  728237      0t0  TCP 127.0.0.1:5052 (LISTEN)

Do you have any ideas what it could be?

**Comment by timmyers** [comment]
Seeing a similar error
```
time="2020-04-16T15:56:34Z" level=error msg="[main] setting up: prysm: getting version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: address http://localhost:4000: too many colons in address\""
```
with `--beacon.addr=http://localhost:4000`

**Comment by tzapu** [comment]
hey 
@Youllneverknow0 for lighthouse we are connecting over http so the beacon.addr flag should be `--beacon.addr="http://localhost:5052"`
@timmyers for prysm we are using grpc so the relevant flags should be something like
```
--beacon.addr="localhost:4000" \
--beacon.metrics-addr="http://localhost:8080/metrics"
```

i get how this is confusing, it mostly stems from lack of stndardisation but it of course could do with some better error messages. in the mean time I have also added a new onboarding page https://eth2stats.io/add-node which should help with small but annoying things like these

(will leave this open till i add more meaningful error messages)

**Comment by Youllneverknow0** [comment]
This does indeed help. Thank you tzapu.

It seems to be running now but not connecting.

INFO[0000] Could not load config file. Falling back to args. Error: Config File "config" Not Found in "[/home/ubuntu/eth2stats-client]"  module=main
INFO[0000] [core] setting up eth2stats server connection
WARN[0001] [core] token file not found; will register as new client
INFO[0001] [core] getting beacon client version
INFO[0001] [core] got beacon client version              version=Lighthouse/v0.1.0-unstable/aarch64-linux
INFO[0001] [core] getting beacon client genesis time
INFO[0001] [core] got beacon client genesis time         genesisTime=1581670800
**INFO[0001] [core] awaiting connection to eth2stats server**

With this message it gets stuck.

**Comment by tzapu** [comment]
hey, in your intial post i m seeing `--eth2stats.addr="grc.summer.eth2stats.io:443"`
that should be `--eth2stats.addr="grc.summer.eth2stats.io:443"`

let me know how you get on
cheers
alex

**Comment by Youllneverknow0** [comment]
That was it. Didn‘t see the typo.
It was very attentive of you.
Now it works.
Thank you!
