### ISSUE TITLE
New Onyx Testnet & Sunsetting of Topaz

### ISSUE THREAD

**Issue by prestonvanloon** [Alethio/eth2stats-client#37]
Hi Alethio team,

@prysmaticlabs has announced a new testnet, Onyx. 
Could we have a new tab and endpoint for Onyx nodes?

Announcement: https://medium.com/prysmatic-labs/introducing-the-onyx-testnet-6dadbd95d873

**Comment by prestonvanloon** [comment]
Genesis time is 1592111844.

```javascript
new Date(1592111844 * 1000)
Sat Jun 13 2020 22:17:24 GMT-0700 (Pacific Daylight Time)
```

**Comment by tzapu** [comment]
and we re live, thank you

https://eth2stats.io/onyx-testnet
