### ISSUE TITLE
`nimbus` missing from `add your node`

### ISSUE THREAD

**Issue by arnetheduck** [Alethio/eth2stats-client#38]
Hey, looks like nimbus is missing from the `add your node` dropdown of client type - any chance it can be thrown in there?

**Comment by tzapu** [comment]
hi , sure

could you please let me know if this seems correct?

```
  {
        type: "nimbus",
        beaconAddr: "http://localhost:9000",
        beaconAddrDetails: "HTTP endpoint for the beacon chain node's RESTful JSON API",
        metricsAddr: "http://localhost:8008/metrics",
        metricsEnabled: true
    },
```

mostly the REST API port and if metrics are supported.

cheers
alex

**Comment by arnetheduck** [comment]
Hey - yeah, I have metrics on 8008, and by default the rpc will run on `9090` - `9000` is for libp2p.

**Comment by arnetheduck** [comment]
nice! I managed to get it up and running - node `atd0`

**Comment by tzapu** [comment]
added, thanks!
