### ISSUE TITLE
eth2stats adds a new gRPC connection to the prysm node every 12 seconds until the OS runs out of file handlers

### ISSUE THREAD

**Issue by timjp87** [Alethio/eth2stats-client#45]
Hi,

I added my prysm node (alpha17) to eth2stats this morning.  Later in the afternoon it dropped of the stats board so I looked into the tmux session running my node and noticed it is throwing errors, because it can't open any file handles anymore. I also saw that it's logging out "New gRPC connection to beacon node" with a new port every 12 seconds. I simply rebooted the device and everything was back to normal. I investigated what these port are about and saw that all these connections are ESTABLISHED when I look into lsof. After stopping the container it immediately stops adding new connections. Must be because of the pre-genesis condition. I will turn the container back on after genesis otherwise it will crash the node again.

![Bildschirmfoto 2020-07-31 um 19 39 15](https://user-images.githubusercontent.com/3089763/89062930-98fc8680-d367-11ea-8fc0-d865974f773e.png)

**Comment by LarsHolte** [comment]
Same issue here also with Prysm alpha.17 pre-genesis.

Additional log which repeats every 12s from the eth2stats docker container (v0.0.11+0f09fd5):
```
time="2020-08-01T03:20:56Z" level=info msg="[main] retrying..."
time="2020-08-01T03:20:56Z" level=info msg="[prysm] setting up beacon client connection"
time="2020-08-01T03:20:56Z" level=warning msg="[prysm] no tls certificate provided; will use insecure connection to beacon chain"
time="2020-08-01T03:20:56Z" level=info msg="[core] setting up eth2stats server connection"
time="2020-08-01T03:20:56Z" level=info msg="[core] getting beacon client version"
time="2020-08-01T03:20:56Z" level=info msg="[core] got beacon client version" version="Prysm/v1.0.0-alpha.17/f414cf36b99dea2d997d0141acb3d1a319fb5578. Built at: 2020-07-31 03:00:47+00:00"
time="2020-08-01T03:20:56Z" level=info msg="[core] getting beacon client genesis time"
time="2020-08-01T03:20:56Z" level=info msg="[core] beacon client genesis time" genesisTime=0
time="2020-08-01T03:20:56Z" level=info msg="[core] awaiting connection to eth2stats server"
time="2020-08-01T03:20:56Z" level=info msg="[core] getting chain head for initial feed"
time="2020-08-01T03:20:56Z" level=error msg="[main] setting up: prysm: getting chain head: rpc error: code = Internal desc = Head block of chain was nil"
```

After beacon chain stops functioning properly journalctl also logs many of type:
`Jul 31 13:12:39 beacon01 prysm.sh[752]: 2020/07/31 13:12:39 http: Accept error: accept tcp [::]:8082: accept4: too many open files; retrying in 5ms`

**Comment by canbal99** [comment]
Started to see this problem again.
Prysm/LocalBuild/e5ed2cd141df40627c7636aef4cac6325d6719e1. Built at: 2020-10-14T21:54:02+0200 (my own)
eth2stats-client version v0.0.15+b8f8607

Beaconchain logs:
[beaconchain.log](https://github.com/Alethio/eth2stats-client/files/5386978/beaconchain.log)

**Comment by canbal99** [comment]
Even after I remove "--beacon.metrics-addr" from eth2stats-client, I had the same problem.
Prysm client had issues after running a couple of hours.
Issue solved after disabling Prometheus (i was using it with Prysm dashboard).
So apparently it is not related with eth2stats this time...
