### ISSUE TITLE
Eth2Stats client using 1.5GB memory

### ISSUE THREAD

**Issue by michaelsproul** [Alethio/eth2stats-client#64]
While investigating an OOM killing, I noticed eth2stats-client using 1.5GB of memory, which is a lot more than I've ever seen it use previously. I'm using the latest `v1` node type with Lighthouse v0.3.0:

```sh
~/eth2stats-client/eth2stats-client run \
        --eth2stats.node-name="$node_name" \
        --data.folder ~/.eth2stats/data \
        --eth2stats.addr="grpc.medalla.eth2stats.io:443" --eth2stats.tls=true \
        --beacon.type="v1" \
        --beacon.addr="http://localhost:5052" \
        --beacon.metrics-addr="http://localhost:5054/metrics"
```

My only hunch about what it could be is the attestation pool. Lighthouse hoards a lot of attestations in its pool during periods without finality, e.g. I currently have 329822 attestations, which consume 188MB as a JSON response from `/eth/v1/beacon/pool/attestations`. Still, this in an order of magnitude lower than the amount of memory eth2stats is consuming.

When I restarted the client its memory usage quickly jumped back up to around 1.3GB:

<img width="1278" alt="eth2stats-client" src="https://user-images.githubusercontent.com/4452260/95921138-79b8b580-0dfc-11eb-9d69-5381be314247.png">

Version: `eth2stats-client version v0.0.14+1455e8d`

**Comment by protolambda** [comment]
Thanks for opening an issue! Was also chatting with Paul/Age about the same problem. Try release v0.0.15, that disables the pool queries, and should improve performance.

**Comment by RoBiK75** [comment]
came in here to report the same
`39c6efa8870a        lighthouse-eth2stats    0.19%               2.553GiB / 7.762GiB   32.89%              0B / 0B             3.31GB / 0B         15`

**Comment by michaelsproul** [comment]
I'm running v0.14.0 now with Lighthouse v0.3.1 and there is no longer any issues (Lighthouse's op pool is under control as of v0.3.1)

**Comment by michaelsproul** [comment]
Resolved
