### ISSUE TITLE
Take into account peer state for standard API

### ISSUE THREAD

**Issue by michaelsproul** [Alethio/eth2stats-client#66]
Lighthouse nodes currently have their peer count overstated on eth2stats.io because `eth2stats-client` ignores the peer states when reading `/eth/v1/node/peers`. I think it should use the `state` field to work out which peers are connected.

E.g. eth2-stats reports this number:

```
$ curl -s "http://localhost:5052/eth/v1/node/peers" | jq '.data | length'
244
```

when it should report:

```
$ curl -s "http://localhost:5052/eth/v1/node/peers" | jq '.data | map(select(.state == "connected")) | length'
50
```

**Comment by michaelsproul** [comment]
Related https://github.com/ethereum/eth2.0-APIs/pull/101 (adds peer filtering by state to the API)

**Comment by protolambda** [comment]
implementing this now
